

export const RpcMethods = {
  systemInfo: 'system.info',
  systemRestart: 'system.restart',
  modelSettingsGet: 'model_settings.get',
  modelSettingsUpdate: 'model_settings.update',
  modelSettingsTest: 'model_settings.test',
  conversationList: 'conversation.list',
  conversationGet: 'conversation.get',
  conversationCreate: 'conversation.create',
  conversationSend: 'conversation.send',
  conversationRename: 'conversation.rename',
  conversationDelete: 'conversation.delete',
  runList: 'run.list',
  runGet: 'run.get',
  runCancel: 'run.cancel',
  runInterrupt: 'run.interrupt',
  runRecover: 'run.recover',
  traceGet: 'trace.get',
  automationList: 'automation.list',
  automationGet: 'automation.get',
  automationCreate: 'automation.create',
  automationPause: 'automation.pause',
  automationResume: 'automation.resume',
  automationCancel: 'automation.cancel',
  approvalList: 'approval.list',
  approvalGet: 'approval.get',
  approvalApprove: 'approval.approve',
  approvalDeny: 'approval.deny',
  artifactList: 'artifact.list',
  artifactGet: 'artifact.get',
  memoryList: 'memory.list',
  taskList: 'task.list',
  taskGet: 'task.get',
  taskPlanAccept: 'task.plan_accept',
  taskPlanReject: 'task.plan_reject',
  meaStart: 'mea.start',
  meaGet: 'mea.get',
  meaList: 'mea.list',
  meaTools: 'mea.tools',
  meaAnswer: 'mea.answer',
  meaNote: 'mea.note',
  meaPause: 'mea.pause',
  meaResume: 'mea.resume',
  meaCancel: 'mea.cancel',
  extensionList: 'extension.list',
  extensionImportPreview: 'extension.import.preview',
  extensionImportApply: 'extension.import.apply',
  skillInstall: 'skill.install',
  skillSetEnabled: 'skill.set_enabled',
  skillDelete: 'skill.delete',
  mcpAdd: 'mcp.add',
  mcpSetEnabled: 'mcp.set_enabled',
  mcpDelete: 'mcp.delete',
} as const

export type RpcMethodName = (typeof RpcMethods)[keyof typeof RpcMethods]


export const RpcMethodErrorCode = {
  ParseError: -32700,
  InvalidRequest: -32600,
  MethodNotFound: -32601,
  InvalidParams: -32602,
  InternalError: -32603,
  ResourceNotFound: -32000,
  InvalidState: -32001,
} as const
